name: fccthegurukul_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.3 # Updated  google_sign_in: ^6.2.1
#  flutter_local_notifications: ^19.5.0
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.10.0
  device_info_plus: ^12.2.0
  uuid: ^4.5.1
  http: ^1.2.2
  google_sign_in: ^7.2.0
  onesignal_flutter: ^5.3.4
  go_router: ^17.0.0
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.2.1
  pod_player: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  shaders:
#    - shaders/ink_sparkle.frag